# Generated by Django 6.0.6 on 2026-06-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='starts_at',
            new_name='date',
        ),
    ]
