# Generated by Django 6.0.6 on 2026-06-26 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_rename_starts_at_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='max_participants',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
